version: '3.8'

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  tensorflow-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MAX_CONCURRENT_WORKERS=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - API_KEY=${API_KEY}
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    mem_swappiness: 0
    oom_kill_disable: false
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:

# Add automatic cleanup for unused images and containers
x-auto-cleanup:
  prune:
    image: docker:cli
    command: >
      sh -c "
        docker system prune -af --filter 'until=24h'
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock